Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\autopy\cha11\test.py", line 4, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
